### ISSUE TITLE
Running the interceptor on a 64 bit system

### ISSUE THREAD

**Issue by razvand** [systems-cs-pub-ro/executable-interceptor#1]
I'm running the app on a 64 bit system and I get the following. It doesn't work. It's because of the 64 bit system?

```
$ PYTHONPATH=../../pyelftools/ python elf32_injector.py test/hellob test/print_id_intcerp 
$ ./test/hellob 
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!
```

**Comment by octavian-crintea** [comment]
I receive a segfault when I run it.  The Python program is not supposed to run on a 64 bit system.  For example, I hardcoded the GOT entry size to be 4 bytes, which is not the case on this type of OS.

**Comment by razvand** [comment]
OK. You should add this in the README. I will close this issue.
